const endPoints = {
  AUTHENTICATE_USER: `PAF/authenticate`,
  LOGIN_USER: `PAF/login`,
  RESET_PASSWORD:`PAF/login/resetPassword/`,
  FORGOT_PASSWORD:`PAF/login/forgotPassword/`,
  GET_INDICATORS_BY_DOMAIN_ID: `PAF/rubrics/indicatorsByDomainId/`,
  GET_DASHBOARD_DETAILS_OBSERVATION: 'PAF/teachers/observation/dashBoard/',
  GET_ALL_USERS: `PAF/users/all`,
  GET_USER: `PAF/users/`,
  GET_ALL_USER_GROUPS: `PAF/userGroups/all`,
  GET_USER_GROUPS: `PAF/userGroups/`,
  GET_ALL_DOMAINS: `PAF/metadata/domains`,
  GET_DOMAINS_BY_ID: `PAF/rubrics/indicatorsByDomainId/`,
  SAVE_EVIDENCE_CARD: `PAF/teachers/saveEvidence`,
  GET_OBSERVATION_BY_ID: `PAF/teachers/observation/`,
  GET_ALL_OBSERVATIONS: `PAF/teachers/observation/getAllObservation/search/`,
  UPDATE_EVIDENCE_CARD:`PAF/teachers/updateEvidence/`,
  SAVE_OBSERVATION:`PAF/teachers/saveObservation`,
  UPDATE_OBSERVATION:`PAF/teachers/updateObservation/`,
  GET_EVIDENCE_BY_ID: `PAF/teachers/evidence/`,
  DELETE_ATTACHMENTS:`PAF/teachers/deleteAttachment`,
  GET_ALL_RUBRICS: `PAF/rubrics/all`,
  DELETE_RUBRIC: `PAF/rubrics`,
  UPDATE_RUBRIC:`PAF/rubrics/`,
  GET_RUBRIC: `PAF/rubrics/`,
  GET_ALL_FLOWS: `PAF/flows/all?loggedInUserName=`,
  GET_FLOW_BY_ID: `PAF/flows/`,
  GET_FORM_BY_ID: `PAF/forms/`,
  DELETE_FLOWS:`PAF/flows`,
  DELETE_FORMS:`PAF/forms?`,
  GET_ROLES:`PAF/metadata/roles`,
  GET_STATES:`PAF/metadata/states`,
  GET_DISTRICTS:`PAF/metadata/districts`,
  GET_AREAS:`PAF/metadata/areas`,
  GET_SCHOOLS:`PAF/metadata/schools`,
  GET_QUESTION_RATING_BY_INDICATOR_ID:`PAF/forms/getQuestionRatingByIndicatorId/`,
  GET_PREVIEW_FORM: `PAF/forms/previewForm/`,
  DASHBOARD_FILTER: `PAF/teachers/observation/dashBoardFilter/`,
  SUBMIT_FORM_RESPONSE:`PAF/forms/submitFormResponse`,
  ACCEPTING_RESPONSES:`PAF/forms/acceptResponse`,
  GET_PENDING_USERS_LIST_FOR_SEND_REMINDER:`PAF/forms/getPendingUserListForSendReminder/`,
  SEND_REMINDER_TO_ALL_PENDING_USERS:`PAF/flows/sendReminder/`,
  SEND_REMINDER_TO_USER_GROUPS:`PAF/flows/sendFormAssignmentReminder/`,
  ASSIGN_FLOW_TO_USERS_AND_USER_GROUPS:`PAF/flows/assignFlowToUsersAndGroups`,
  ASSIGN_FORM_TO_USERS_AND_GROUPS:`PAF/forms/assignUsersAndGroups`,
  SCHEDULE_REMINDER_DATE:`PAF/flows/scheduleReminder?`,

};
export default endPoints;
