const endPoints = {
  AUTHENTICATE_USER: `authenticate`,
  LOGIN_USER: `login`,
  UPDATE_USER: `users/`,
  RESET_PASSWORD: `login/resetPassword/`,
  DELETE_USER_PHOTO: `users/photo/`,
  UPDATE_USER_PHOTO: `users/photo/`,
  FORGOT_PASSWORD: `login/forgotPassword/`,
  GET_INDICATORS_BY_DOMAIN_ID: `rubrics/indicatorsByDomainId/`,
  GET_DASHBOARD_DETAILS_OBSERVATION: 'teachers/observation/dashBoard/',
  GET_ALL_USERS: `users/all`,
  GET_USER: `users/`,
  GET_USERS_BY_SEARCH: `users/search?`,
  GET_ALL_USER_GROUPS: `userGroups/all`,
  GET_USER_GROUPS_BY_SEARCH: `userGroups/search?`,
  GET_USER_GROUPS: `userGroups/`,
  GET_ALL_DOMAINS: `metadata/domains`,
  GET_DOMAINS_BY_ID: `rubrics/indicatorsByDomainId/`,
  SAVE_EVIDENCE_CARD: `teachers/saveEvidence`,
  GET_OBSERVATION_BY_ID: `teachers/observation/`,
  GET_ALL_OBSERVATIONS: `teachers/observation/getAllObservation/search/`,
  UPDATE_EVIDENCE_CARD: `teachers/updateEvidence/`,
  SAVE_OBSERVATION: `teachers/saveObservation`,
  UPDATE_OBSERVATION: `teachers/updateObservation/`,
  GET_EVIDENCE_BY_ID: `teachers/evidence/`,
  DELETE_ATTACHMENTS: `teachers/deleteAttachment`,
  GET_ALL_RUBRICS: `rubrics/all`,
  DELETE_RUBRIC: `rubrics`,
  UPDATE_RUBRIC: `rubrics/`,
  GET_RUBRIC: `rubrics/`,
  GET_ALL_FLOWS: `flows/all?loggedInUserName=`,
  GET_FLOW_BY_ID: `flows/`,
  GET_FORM_BY_ID: `forms/`,
  DELETE_FLOWS: `flows`,
  DELETE_FORMS: `forms?`,
  GET_ROLES: `metadata/roles`,
  GET_STATES: `metadata/states`,
  GET_DISTRICTS: `metadata/districts`,
  GET_AREAS: `metadata/areas`,
  GET_SCHOOLS: `metadata/schools`,
  GET_ROLES_BY_SEARCH: `roles/search?`,
  GET_STATES_BY_SEARCH: `states/search?`,
  GET_DISTRICTS_BY_SEARCH: `districts/search?`,
  GET_AREAS_BY_SEARCH: `areas/search?`,
  GET_SCHOOLS_BY_SEARCH: `schools/search?`,
  GET_QUESTION_RATING_BY_INDICATOR_ID: `forms/getQuestionRatingByIndicatorId/`,
  GET_PREVIEW_FORM: `forms/previewForm/`,
  DASHBOARD_FILTER: `teachers/observation/dashBoardFilter/`,
  SUBMIT_FORM_RESPONSE: `forms/submitFormResponse`,
  ACCEPTING_RESPONSES: `forms/acceptResponse`,
  GET_PENDING_USERS_LIST_FOR_SEND_REMINDER: `forms/getPendingUserListForSendReminder/`,
  SEND_REMINDER_TO_ALL_PENDING_USERS: `flows/sendReminder/`,
  SEND_REMINDER_TO_USER_GROUPS: `flows/sendFormAssignmentReminder/`,
  ASSIGN_FLOW_TO_USERS_AND_USER_GROUPS: `flows/assignFlowToUsersAndGroups`,
  ASSIGN_FORM_TO_USERS_AND_GROUPS: `forms/assignUsersAndGroups`,
  SCHEDULE_REMINDER_DATE: `flows/scheduleReminder?`,
  PRINT_FORM_RESPONSES: `forms/printIndResponse`,
  PRINT_QUESTION_WISE_RESPONSES: `forms/printQuestionWiseResponse`,
  USER_COUNT_ANAYTICS: `analytics/userCountAnalytics`,
  USER_COUNT_ANAYTICS_USER_AND_ROLE:`analytics/userCountAnalytics`,
  USER_AND_ROLE_COUNT_ANALYTICS:`analytics/userAndRoleCountAnalytics`,
  GET_FORM_ASSIGNED_USER_AND_USER_GROUPS:`forms/getUsersAndGroups/`,
  GET_FORM_ANALYTICS:`analytics/formAnalytics/`,
  GET_FORM_COUNT_AND_RESPONSE:`analytics/countOfFormAndResponse`,
  LOCATION_IN_COUNT_SYSTEM:`analytics/countOfStateAndAreaAndSchool`,
  OBSERVATION_ANALYTICS_BY_USER_ID:`analytics/teacherObservation/observationByUserId`,
  OBSERVATION_COUNT_ANALYTICS:`analytics/teacherObservation/observation`,
  RUBRIC_WIESE_OBSERVATION:`analytics/teacherObservation/rubric`,
  GET_TEACHER_OBSERVATION_COUNTS:`analytics/teacherObservation`,
  GET_STATES_ANALYTICS:`analytics/metadata/states`,
  GET_AREAS_ANALYTICS:`analytics/metadata/areas`,
  GET_AREAS_SCHOOL:`analytics/metadata/schools`,
  GET_DISTRICS_ANALYTICS:`analytics/metadata/districts`,
  GET_INDICATORS:`rubrics/indicatorsByNameSearch?searchCriteria=`,
  USER_SEARCH_LIST:`analytics/metadata/search`,
  USER_SEARCH_LIST_BY_ID:`analytics/metadata/search`,
  ANALYTICS_DASHBOARD_FILTER: `analytics/metadata/observation/dashBoardFilter/`,
  ANALYTICS_OBSERVATION_BY_ID:`analytics/metadata/observation/`,
  ANALYTICS_SEARCH:`analytics/metadata/search?searchCriteria=`,
  ALL_USER_NOTIFICATION:`notification/allUserNotification/`,
  CREATE_NOTIFICATION:`notification/newEvent`,
  NOTIFICATION_FLAG_UPDATE:`notification/updateUser?`,
  COUNT_OF_STATE_DISTRICT_SCHOOL:`analytics/countOfStateAndAreaAndSchool`
  

}
export default endPoints;
